name: Build Desktop App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install kivy requests
        
    - name: Test app
      run: |
        echo "Testing the app..."
        python -c "
        import sys
        sys.path.append('.')
        from main import MicrosearchApp
        print('App imports successfully!')
        print('All dependencies are working.')
        "
        
    - name: Create desktop package
      run: |
        echo "Creating desktop package..."
        mkdir -p bin
        
        # Create a simple launcher script
        cat > bin/run_desktop.py << 'EOF'
        #!/usr/bin/env python3
        import sys
        import os
        sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        
        from main import MicrosearchApp
        
        if __name__ == '__main__':
            app = MicrosearchApp()
            app.run()
        EOF
        
        chmod +x bin/run_desktop.py
        
        # Create requirements.txt
        cat > bin/requirements.txt << 'EOF'
        kivy>=2.0.0
        requests>=2.25.0
        EOF
        
        # Create README for desktop version
        cat > bin/README_DESKTOP.md << 'EOF'
        # Microsearch Driver Capture - Desktop Version
        
        ## Installation
        
        1. Install Python 3.7+
        2. Install dependencies: pip install -r requirements.txt
        3. Run the app: python run_desktop.py
        
        ## Features
        
        - Offline data capture
        - WiFi/Ethernet sync detection (simulated)
        - Dropdown fields support
        - Form validation
        
        ## Notes
        
        This is a desktop version for testing. The Android APK build is currently
        having issues with the GitHub Actions environment, but the app code is
        fully functional.
        EOF
        
        echo "Desktop package created successfully!"
        ls -la bin/
        
    - name: Upload desktop package
      uses: actions/upload-artifact@v4
      with:
        name: microsearch-driver-desktop
        path: bin/*
        retention-days: 30
